# Change these first
owner: deSHELL # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Gitea Service
    url: https://git.coderrrrr.site
  - name: Vaultwarden
    url: https://vw.coderrrrr.site
  # - name: Go To Social Service
  #   url: https://gts.coderrrrr.site

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.coderrrrr.site
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptimer
  introTitle: "**Uptimer** is the uptime monitor and status page."
  introMessage: This is a status page which uses **real-time** data from my services. Using GitHub Actions, Issues, and Pages to host this.
  navbar:
    - title: Status
      href: /
    - title: Human Reporting
      href: mailto:dev@deva.is-cool.dev?subject=%5BSERVICE%20DOWN!%5D%20One%20of%20your%20services%20is%20DOWN!%20-%20Anonymous%20Helper&body=Hey%20Coderrrrr%2C%20wanted%20to%20say%20that%20one%20of%20your%20services%20is%20DOWN!%0AFIX%20IT%20IMMEDIATELY!!!

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
